// 60 Cümlenin Tam Dilbilgisel ve Terapi Veri Tabanı (DKT Standartlarında)
// Colorful Semantics (Renkli Semantik):
// Özne (KİM?) -> Sarı/Turuncu
// Nesne / Yer (NEYİ? / NEREYE?) -> Açık Mavi
// Eylem / Yüklem (NE YAPTI?) -> Pembe / Kırmızı

const SENTENCE_DATA = [
  // --- 1. YEMEK YEMEK ---
  {
    id: "yemek_ben",
    category: "yemek",
    categoryTitle: "Yemek Yemek",
    subject: "Ben",
    subjectKey: "ben",
    object: "yemek",
    objectKey: "yemek",
    verb: "yedim",
    verbKey: "yedim",
    fullSentence: "Ben yemek yedim",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Kendim çorba/yemek yedim."
  },
  {
    id: "yemek_sen",
    category: "yemek",
    categoryTitle: "Yemek Yemek",
    subject: "Sen",
    subjectKey: "sen",
    object: "yemek",
    objectKey: "yemek",
    verb: "yedin",
    verbKey: "yedin",
    fullSentence: "Sen yemek yedin",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Karşımdaki arkadaşım yemek yedi."
  },
  {
    id: "yemek_o",
    category: "yemek",
    categoryTitle: "Yemek Yemek",
    subject: "O",
    subjectKey: "o",
    object: "yemek",
    objectKey: "yemek",
    verb: "yedi",
    verbKey: "yedi",
    fullSentence: "O yemek yedi",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Diğer arkadaşımız yemek yedi."
  },
  {
    id: "yemek_biz",
    category: "yemek",
    categoryTitle: "Yemek Yemek",
    subject: "Biz",
    subjectKey: "biz",
    object: "yemek",
    objectKey: "yemek",
    verb: "yedik",
    verbKey: "yedik",
    fullSentence: "Biz yemek yedik",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Hep birlikte yemek yedik."
  },

  // --- 2. TOP ATMAK ---
  {
    id: "top_ben",
    category: "top",
    categoryTitle: "Top Atmak",
    subject: "Ben",
    subjectKey: "ben",
    object: "topu",
    objectKey: "top",
    verb: "attım",
    verbKey: "attim",
    fullSentence: "Ben topu attım",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Topu ben fırlattım."
  },
  {
    id: "top_sen",
    category: "top",
    categoryTitle: "Top Atmak",
    subject: "Sen",
    subjectKey: "sen",
    object: "topu",
    objectKey: "top",
    verb: "attın",
    verbKey: "attin",
    fullSentence: "Sen topu attın",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Topu sen fırlattın."
  },
  {
    id: "top_o",
    category: "top",
    categoryTitle: "Top Atmak",
    subject: "O",
    subjectKey: "o",
    object: "topu",
    objectKey: "top",
    verb: "attı",
    verbKey: "atti",
    fullSentence: "O topu attı",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Topu o fırlattı."
  },
  {
    id: "top_biz",
    category: "top",
    categoryTitle: "Top Atmak",
    subject: "Biz",
    subjectKey: "biz",
    object: "topu",
    objectKey: "top",
    verb: "attık",
    verbKey: "attik",
    fullSentence: "Biz topu attık",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Birlikte topu attık."
  },

  // --- 3. SU İÇMEK ---
  {
    id: "su_ben",
    category: "su",
    categoryTitle: "Su İçmek",
    subject: "Ben",
    subjectKey: "ben",
    object: "su",
    objectKey: "su",
    verb: "içtim",
    verbKey: "ictim",
    fullSentence: "Ben su içtim",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Bardaktan suyu ben içtim."
  },
  {
    id: "su_sen",
    category: "su",
    categoryTitle: "Su İçmek",
    subject: "Sen",
    subjectKey: "sen",
    object: "su",
    objectKey: "su",
    verb: "içtin",
    verbKey: "ictin",
    fullSentence: "Sen su içtin",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Bardaktan suyu sen içtin."
  },
  {
    id: "su_o",
    category: "su",
    categoryTitle: "Su İçmek",
    subject: "O",
    subjectKey: "o",
    object: "su",
    objectKey: "su",
    verb: "içti",
    verbKey: "icti",
    fullSentence: "O su içti",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Suyu o içti."
  },
  {
    id: "su_biz",
    category: "su",
    categoryTitle: "Su İçmek",
    subject: "Biz",
    subjectKey: "biz",
    object: "su",
    objectKey: "su",
    verb: "içtik",
    verbKey: "ictik",
    fullSentence: "Biz su içtik",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Hep beraber su içtik."
  },

  // --- 4. OKULA GİTMEK ---
  {
    id: "okul_ben",
    category: "okul",
    categoryTitle: "Okula Gitmek",
    subject: "Ben",
    subjectKey: "ben",
    object: "okula",
    objectKey: "okula",
    verb: "gittim",
    verbKey: "gittim",
    fullSentence: "Ben okula gittim",
    hasObject: true,
    objectType: "yer",
    personSuffix: "-m",
    hint: "Çantamı aldım, okula ben gittim."
  },
  {
    id: "okul_sen",
    category: "okul",
    categoryTitle: "Okula Gitmek",
    subject: "Sen",
    subjectKey: "sen",
    object: "okula",
    objectKey: "okula",
    verb: "gittin",
    verbKey: "gittin",
    fullSentence: "Sen okula gittin",
    hasObject: true,
    objectType: "yer",
    personSuffix: "-n",
    hint: "Çantanı aldın, okula sen gittin."
  },
  {
    id: "okul_o",
    category: "okul",
    categoryTitle: "Okula Gitmek",
    subject: "O",
    subjectKey: "o",
    object: "okula",
    objectKey: "okula",
    verb: "gitti",
    verbKey: "gitti",
    fullSentence: "O okula gitti",
    hasObject: true,
    objectType: "yer",
    personSuffix: "ø",
    hint: "O okula gitti."
  },
  {
    id: "okul_biz",
    category: "okul",
    categoryTitle: "Okula Gitmek",
    subject: "Biz",
    subjectKey: "biz",
    object: "okula",
    objectKey: "okula",
    verb: "gittik",
    verbKey: "gittik",
    fullSentence: "Biz okula gittik",
    hasObject: true,
    objectType: "yer",
    personSuffix: "-k",
    hint: "Birlikte el ele okula gittik."
  },

  // --- 5. OTURMAK (2 Öğeli) ---
  {
    id: "otur_ben",
    category: "oturmak",
    categoryTitle: "Oturmak",
    subject: "Ben",
    subjectKey: "ben",
    object: null,
    objectKey: null,
    verb: "oturdum",
    verbKey: "oturdum",
    fullSentence: "Ben oturdum",
    hasObject: false,
    objectType: null,
    personSuffix: "-m",
    hint: "Sandalyeye ben oturdum."
  },
  {
    id: "otur_sen",
    category: "oturmak",
    categoryTitle: "Oturmak",
    subject: "Sen",
    subjectKey: "sen",
    object: null,
    objectKey: null,
    verb: "oturdun",
    verbKey: "oturdun",
    fullSentence: "Sen oturdun",
    hasObject: false,
    objectType: null,
    personSuffix: "-n",
    hint: "Sandalyeye sen oturdun."
  },
  {
    id: "otur_o",
    category: "oturmak",
    categoryTitle: "Oturmak",
    subject: "O",
    subjectKey: "o",
    object: null,
    objectKey: null,
    verb: "oturdu",
    verbKey: "oturdu",
    fullSentence: "O oturdu",
    hasObject: false,
    objectType: null,
    personSuffix: "ø",
    hint: "Sandalyeye o oturdu."
  },
  {
    id: "otur_biz",
    category: "oturmak",
    categoryTitle: "Oturmak",
    subject: "Biz",
    subjectKey: "biz",
    object: null,
    objectKey: null,
    verb: "oturduk",
    verbKey: "oturduk",
    fullSentence: "Biz oturduk",
    hasObject: false,
    objectType: null,
    personSuffix: "-k",
    hint: "Yan yana oturduk."
  },

  // --- 6. YÜRÜMEK (2 Öğeli) ---
  {
    id: "yuru_ben",
    category: "yurumek",
    categoryTitle: "Yürümek",
    subject: "Ben",
    subjectKey: "ben",
    object: null,
    objectKey: null,
    verb: "yürüdüm",
    verbKey: "yurudum",
    fullSentence: "Ben yürüdüm",
    hasObject: false,
    objectType: null,
    personSuffix: "-m",
    hint: "Yolda ben yürüdüm."
  },
  {
    id: "yuru_sen",
    category: "yurumek",
    categoryTitle: "Yürümek",
    subject: "Sen",
    subjectKey: "sen",
    object: null,
    objectKey: null,
    verb: "yürüdün",
    verbKey: "yurudun",
    fullSentence: "Sen yürüdün",
    hasObject: false,
    objectType: null,
    personSuffix: "-n",
    hint: "Yolda sen yürüdün."
  },
  {
    id: "yuru_o",
    category: "yurumek",
    categoryTitle: "Yürümek",
    subject: "O",
    subjectKey: "o",
    object: null,
    objectKey: null,
    verb: "yürüdü",
    verbKey: "yurudu",
    fullSentence: "O yürüdü",
    hasObject: false,
    objectType: null,
    personSuffix: "ø",
    hint: "Yolda o yürüdü."
  },
  {
    id: "yuru_biz",
    category: "yurumek",
    categoryTitle: "Yürümek",
    subject: "Biz",
    subjectKey: "biz",
    object: null,
    objectKey: null,
    verb: "yürüdük",
    verbKey: "yuruduk",
    fullSentence: "Biz yürüdük",
    hasObject: false,
    objectType: null,
    personSuffix: "-k",
    hint: "Birlikte neşeyle yürüdük."
  },

  // --- 7. RESİM YAPMAK ---
  {
    id: "resim_ben",
    category: "resim",
    categoryTitle: "Resim Yapmak",
    subject: "Ben",
    subjectKey: "ben",
    object: "resim",
    objectKey: "resim",
    verb: "yaptım",
    verbKey: "yaptim",
    fullSentence: "Ben resim yaptım",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Boyalarla tuvale resmi ben yaptım."
  },
  {
    id: "resim_sen",
    category: "resim",
    categoryTitle: "Resim Yapmak",
    subject: "Sen",
    subjectKey: "sen",
    object: "resim",
    objectKey: "resim",
    verb: "yaptın",
    verbKey: "yaptin",
    fullSentence: "Sen resim yaptın",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Boyalarla tuvale resmi sen yaptın."
  },
  {
    id: "resim_o",
    category: "resim",
    categoryTitle: "Resim Yapmak",
    subject: "O",
    subjectKey: "o",
    object: "resim",
    objectKey: "resim",
    verb: "yaptı",
    verbKey: "yapti",
    fullSentence: "O resim yaptı",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Boyalarla resmi o yaptı."
  },
  {
    id: "resim_biz",
    category: "resim",
    categoryTitle: "Resim Yapmak",
    subject: "Biz",
    subjectKey: "biz",
    object: "resim",
    objectKey: "resim",
    verb: "yaptık",
    verbKey: "yaptik",
    fullSentence: "Biz resim yaptık",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Birlikte harika bir resim yaptık."
  },

  // --- 8. ZIPLAMAK (2 Öğeli) ---
  {
    id: "zipla_ben",
    category: "ziplamak",
    categoryTitle: "Zıplamak",
    subject: "Ben",
    subjectKey: "ben",
    object: null,
    objectKey: null,
    verb: "zıpladım",
    verbKey: "zipladim",
    fullSentence: "Ben zıpladım",
    hasObject: false,
    objectType: null,
    personSuffix: "-m",
    hint: "Kollarımı açıp havaya ben zıpladım."
  },
  {
    id: "zipla_sen",
    category: "ziplamak",
    categoryTitle: "Zıplamak",
    subject: "Sen",
    subjectKey: "sen",
    object: null,
    objectKey: null,
    verb: "zıpladın",
    verbKey: "zipladin",
    fullSentence: "Sen zıpladın",
    hasObject: false,
    objectType: null,
    personSuffix: "-n",
    hint: "Kollarını açıp havaya sen zıpladın."
  },
  {
    id: "zipla_o",
    category: "ziplamak",
    categoryTitle: "Zıplamak",
    subject: "O",
    subjectKey: "o",
    object: null,
    objectKey: null,
    verb: "zıpladı",
    verbKey: "zipladi",
    fullSentence: "O zıpladı",
    hasObject: false,
    objectType: null,
    personSuffix: "ø",
    hint: "Neşeyle havaya o zıpladı."
  },
  {
    id: "zipla_biz",
    category: "ziplamak",
    categoryTitle: "Zıplamak",
    subject: "Biz",
    subjectKey: "biz",
    object: null,
    objectKey: null,
    verb: "zıpladık",
    verbKey: "zipladik",
    fullSentence: "Biz zıpladık",
    hasObject: false,
    objectType: null,
    personSuffix: "-k",
    hint: "Hep beraber neşeyle zıpladık."
  },

  // --- 9. MONT GİYMEK ---
  {
    id: "mont_ben",
    category: "mont",
    categoryTitle: "Mont Giymek",
    subject: "Ben",
    subjectKey: "ben",
    object: "mont",
    objectKey: "mont",
    verb: "giydim",
    verbKey: "giydim",
    fullSentence: "Ben mont giydim",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Kırmızı kışlık montumu ben giydim."
  },
  {
    id: "mont_sen",
    category: "mont",
    categoryTitle: "Mont Giymek",
    subject: "Sen",
    subjectKey: "sen",
    object: "mont",
    objectKey: "mont",
    verb: "giydin",
    verbKey: "giydin",
    fullSentence: "Sen mont giydin",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Kırmızı kışlık montunu sen giydin."
  },
  {
    id: "mont_o",
    category: "mont",
    categoryTitle: "Mont Giymek",
    subject: "O",
    subjectKey: "o",
    object: "mont",
    objectKey: "mont",
    verb: "giydi",
    verbKey: "giydi",
    fullSentence: "O mont giydi",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Montunu o giydi."
  },
  {
    id: "mont_biz",
    category: "mont",
    categoryTitle: "Mont Giymek",
    subject: "Biz",
    subjectKey: "biz",
    object: "mont",
    objectKey: "mont",
    verb: "giydik",
    verbKey: "giydik",
    fullSentence: "Biz mont giydik",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Hava soğuk olduğu için montlarımızı giydik."
  },

  // ========================================================================
  // YENİ GENİŞLETİLMİŞ DKT KÜTÜPHANESİ (KULLANICI TALEBİ)
  // ========================================================================

  // --- 10. KİTAP OKUMAK ---
  {
    id: "kitap_ben",
    category: "kitap",
    categoryTitle: "Kitap Okumak",
    subject: "Ben",
    subjectKey: "ben",
    object: "kitap",
    objectKey: "kitap",
    verb: "okudum",
    verbKey: "okudum",
    fullSentence: "Ben kitap okudum",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Resimli hikaye kitabını ben okudum."
  },
  {
    id: "kitap_sen",
    category: "kitap",
    categoryTitle: "Kitap Okumak",
    subject: "Sen",
    subjectKey: "sen",
    object: "kitap",
    objectKey: "kitap",
    verb: "okudun",
    verbKey: "okudun",
    fullSentence: "Sen kitap okudun",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Resimli hikaye kitabını sen okudun."
  },
  {
    id: "kitap_o",
    category: "kitap",
    categoryTitle: "Kitap Okumak",
    subject: "O",
    subjectKey: "o",
    object: "kitap",
    objectKey: "kitap",
    verb: "okudu",
    verbKey: "okudu",
    fullSentence: "O kitap okudu",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Hikaye kitabını o okudu."
  },
  {
    id: "kitap_biz",
    category: "kitap",
    categoryTitle: "Kitap Okumak",
    subject: "Biz",
    subjectKey: "biz",
    object: "kitap",
    objectKey: "kitap",
    verb: "okuduk",
    verbKey: "okuduk",
    fullSentence: "Biz kitap okuduk",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Birlikte oturup kitap okuduk."
  },

  // --- 11. ELMA YEMEK ---
  {
    id: "elma_ben",
    category: "elma",
    categoryTitle: "Elma Yemek",
    subject: "Ben",
    subjectKey: "ben",
    object: "elma",
    objectKey: "elma",
    verb: "yedim",
    verbKey: "elma_yedim",
    fullSentence: "Ben elma yedim",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Kırmızı tatlı elmayı ben yedim."
  },
  {
    id: "elma_sen",
    category: "elma",
    categoryTitle: "Elma Yemek",
    subject: "Sen",
    subjectKey: "sen",
    object: "elma",
    objectKey: "elma",
    verb: "yedin",
    verbKey: "elma_yedin",
    fullSentence: "Sen elma yedin",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Kırmızı tatlı elmayı sen yedin."
  },
  {
    id: "elma_o",
    category: "elma",
    categoryTitle: "Elma Yemek",
    subject: "O",
    subjectKey: "o",
    object: "elma",
    objectKey: "elma",
    verb: "yedi",
    verbKey: "elma_yedi",
    fullSentence: "O elma yedi",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Kırmızı elmayı o yedi."
  },
  {
    id: "elma_biz",
    category: "elma",
    categoryTitle: "Elma Yemek",
    subject: "Biz",
    subjectKey: "biz",
    object: "elma",
    objectKey: "elma",
    verb: "yedik",
    verbKey: "elma_yedik",
    fullSentence: "Biz elma yedik",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Birlikte elma yedik."
  },

  // --- 12. SÜT İÇMEK ---
  {
    id: "sut_ben",
    category: "sut",
    categoryTitle: "Süt İçmek",
    subject: "Ben",
    subjectKey: "ben",
    object: "süt",
    objectKey: "süt",
    verb: "içtim",
    verbKey: "süt_içtim",
    fullSentence: "Ben süt içtim",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Bardağımdaki taze sütü ben içtim."
  },
  {
    id: "sut_sen",
    category: "sut",
    categoryTitle: "Süt İçmek",
    subject: "Sen",
    subjectKey: "sen",
    object: "süt",
    objectKey: "süt",
    verb: "içtin",
    verbKey: "süt_içtin",
    fullSentence: "Sen süt içtin",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Bardağındaki taze sütü sen içtin."
  },
  {
    id: "sut_o",
    category: "sut",
    categoryTitle: "Süt İçmek",
    subject: "O",
    subjectKey: "o",
    object: "süt",
    objectKey: "süt",
    verb: "içti",
    verbKey: "süt_içti",
    fullSentence: "O süt içti",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Sütünü o içti."
  },
  {
    id: "sut_biz",
    category: "sut",
    categoryTitle: "Süt İçmek",
    subject: "Biz",
    subjectKey: "biz",
    object: "süt",
    objectKey: "süt",
    verb: "içtik",
    verbKey: "süt_içtik",
    fullSentence: "Biz süt içtik",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Hep beraber süt içtik."
  },

  // --- 13. DİŞ FIRÇALAMAK ---
  {
    id: "dis_ben",
    category: "dis",
    categoryTitle: "Diş Fırçalamak",
    subject: "Ben",
    subjectKey: "ben",
    object: "dişimi",
    objectKey: "diş",
    verb: "fırçaladım",
    verbKey: "fırçaladım",
    fullSentence: "Ben dişimi fırçaladım",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Fırçamla dişimi ben temizledim."
  },
  {
    id: "dis_sen",
    category: "dis",
    categoryTitle: "Diş Fırçalamak",
    subject: "Sen",
    subjectKey: "sen",
    object: "dişini",
    objectKey: "diş",
    verb: "fırçaladın",
    verbKey: "fırçaladın",
    fullSentence: "Sen dişini fırçaladın",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Fırçanla dişini sen temizledin."
  },
  {
    id: "dis_o",
    category: "dis",
    categoryTitle: "Diş Fırçalamak",
    subject: "O",
    subjectKey: "o",
    object: "dişini",
    objectKey: "diş",
    verb: "fırçaladı",
    verbKey: "fırçaladı",
    fullSentence: "O dişini fırçaladı",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Dişini o fırçaladı."
  },
  {
    id: "dis_biz",
    category: "dis",
    categoryTitle: "Diş Fırçalamak",
    subject: "Biz",
    subjectKey: "biz",
    object: "dişimizi",
    objectKey: "diş",
    verb: "fırçaladık",
    verbKey: "fırçaladık",
    fullSentence: "Biz dişimizi fırçaladık",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Birlikte dişlerimizi fırçaladık."
  },

  // --- 14. EL YIKAMAK ---
  {
    id: "el_ben",
    category: "el",
    categoryTitle: "El Yıkamak",
    subject: "Ben",
    subjectKey: "ben",
    object: "elimi",
    objectKey: "sabun",
    verb: "yıkadım",
    verbKey: "yıkadım",
    fullSentence: "Ben elimi yıkadım",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-m",
    hint: "Sabun ve suyla elimi ben yıkadım."
  },
  {
    id: "el_sen",
    category: "el",
    categoryTitle: "El Yıkamak",
    subject: "Sen",
    subjectKey: "sen",
    object: "elini",
    objectKey: "sabun",
    verb: "yıkadın",
    verbKey: "yıkadın",
    fullSentence: "Sen elini yıkadın",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-n",
    hint: "Sabun ve suyla elini sen yıkadın."
  },
  {
    id: "el_o",
    category: "el",
    categoryTitle: "El Yıkamak",
    subject: "O",
    subjectKey: "o",
    object: "elini",
    objectKey: "sabun",
    verb: "yıkadı",
    verbKey: "yıkadı",
    fullSentence: "O elini yıkadı",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "ø",
    hint: "Elini o yıkadı."
  },
  {
    id: "el_biz",
    category: "el",
    categoryTitle: "El Yıkamak",
    subject: "Biz",
    subjectKey: "biz",
    object: "elimizi",
    objectKey: "sabun",
    verb: "yıkadık",
    verbKey: "yıkadık",
    fullSentence: "Biz elimizi yıkadık",
    hasObject: true,
    objectType: "nesne",
    personSuffix: "-k",
    hint: "Birlikte ellerimizi yıkadık."
  },

  // --- 15. KOŞMAK (2 Öğeli) ---
  {
    id: "kos_ben",
    category: "kosmak",
    categoryTitle: "Koşmak",
    subject: "Ben",
    subjectKey: "ben",
    object: null,
    objectKey: null,
    verb: "koştum",
    verbKey: "koştum",
    fullSentence: "Ben koştum",
    hasObject: false,
    objectType: null,
    personSuffix: "-m",
    hint: "Hızlıca ben koştum."
  },
  {
    id: "kos_sen",
    category: "kosmak",
    categoryTitle: "Koşmak",
    subject: "Sen",
    subjectKey: "sen",
    object: null,
    objectKey: null,
    verb: "koştun",
    verbKey: "koştun",
    fullSentence: "Sen koştun",
    hasObject: false,
    objectType: null,
    personSuffix: "-n",
    hint: "Hızlıca sen koştun."
  },
  {
    id: "kos_o",
    category: "kosmak",
    categoryTitle: "Koşmak",
    subject: "O",
    subjectKey: "o",
    object: null,
    objectKey: null,
    verb: "koştu",
    verbKey: "koştu",
    fullSentence: "O koştu",
    hasObject: false,
    objectType: null,
    personSuffix: "ø",
    hint: "Hızlıca o koştu."
  },
  {
    id: "kos_biz",
    category: "kosmak",
    categoryTitle: "Koşmak",
    subject: "Biz",
    subjectKey: "biz",
    object: null,
    objectKey: null,
    verb: "koştuk",
    verbKey: "koştuk",
    fullSentence: "Biz koştuk",
    hasObject: false,
    objectType: null,
    personSuffix: "-k",
    hint: "Birlikte yarışarak koştuk."
  }
];

// DKT Kategori Listesi (15 Kategori)
const CATEGORIES = [
  { id: "all", name: "Tüm Eylemler (60)", icon: "✨" },
  { id: "top", name: "Top Atmak", icon: "⚽" },
  { id: "resim", name: "Resim Yapmak", icon: "🎨" },
  { id: "yemek", name: "Yemek Yemek", icon: "🍲" },
  { id: "elma", name: "Elma Yemek", icon: "🍎" },
  { id: "su", name: "Su İçmek", icon: "💧" },
  { id: "sut", name: "Süt İçmek", icon: "🥛" },
  { id: "kitap", name: "Kitap Okumak", icon: "📖" },
  { id: "okul", name: "Okula Gitmek", icon: "🏫" },
  { id: "mont", name: "Mont Giymek", icon: "🧥" },
  { id: "dis", name: "Diş Fırçalamak", icon: "🪥" },
  { id: "el", name: "El Yıkamak", icon: "🧼" },
  { id: "oturmak", name: "Oturmak", icon: "🪑" },
  { id: "yurumek", name: "Yürümek", icon: "🚶" },
  { id: "kosmak", name: "Koşmak", icon: "🏃" },
  { id: "ziplamak", name: "Zıplamak", icon: "🦘" }
];

// Zamir Listesi
const SUBJECTS = [
  { id: "all", name: "Tüm Kişiler" },
  { id: "ben", name: "Ben (1. Tekil)" },
  { id: "sen", name: "Sen (2. Tekil)" },
  { id: "o", name: "O (3. Tekil)" },
  { id: "biz", name: "Biz (1. Çoğul)" }
];
